#!/bin/sh

timespec=$1
shift
nickname=$*

minutes_pattern='^\s*\([0-9]\+\):[0-9]\+\s*$'
seconds_pattern='^\s*\([0-9]\+:\)\?\([0-9]\+\)\s*$'

minutes=$(echo "$timespec" | sed -n "s/$minutes_pattern/\1/p")
seconds=$(echo "$timespec" | sed -n "s/$seconds_pattern/\2/p")

if [ -z "$minutes" ]; then
  minutes=0
fi

seconds=$((seconds + 60*minutes))

if [ -n "$nickname" ]; then
  prefix="$nickname "
fi

print_countdown() {
  remaining=$1
  minutes_left=$((remaining / 60))
  seconds_left=$((remaining % 60))
  display=$(printf '%s%02d:%02d left' "$prefix" "$minutes_left" "$seconds_left")
  printf '\e[0G%s\033]0;%s\007' "$display" "$display"
}

begin=$(date +%s)

while true; do
  now=$(date +%s)
  elapsed=$((now - begin))
  remaining=$((seconds - elapsed))
  if [ "$remaining" -le 0 ]; then
    print_countdown 0
    scriptdir=$(dirname "$(readlink -f "$0")")
    # --gain increases the volume. I think that 2 is twice as loud.
    cvlc --gain 2 "$scriptdir/ring.mp3" 2>/dev/null
    exit
  fi

  if [ "$remaining" = "$previous_remaining" ]; then
    continue
  fi

  previous_remaining=$remaining

  print_countdown "$remaining"
  sleep 0.1
done
printf '\n'

